name: Lambda-triggered session update

on:
  workflow_dispatch:
    inputs:
      s3_session_id:
        required: true
      connect_uid:
        default: "LVC20"
      sched_url:
        default: "https://lvc20.sched.com"

jobs:
  lambda:
    runs-on: self-hosted
    steps:
      - name: Create working directory
        run: mkdir -p "$GITHUB_WORKSPACE/tasks"

      - name: Lambda trigger
        run: >-
          docker run --rm -i
          -e bamboo_connect_uid=${{ github.event.inputs.connect_uid }}
          -e bamboo_s3_session_id=${{ github.event.inputs.s3_session_id }}
          -e bamboo_sched_url=${{ github.event.inputs.sched_url }}
          -e bamboo_sched_password=${{ secrets.SCHED_PASSWORD }}
          -e bamboo_working_directory="/app/work_dir"
          -v "$GITHUB_WORKSPACE/tasks":/app/work_dir
          -u=$(id -u):$(id -g)
          linaroits/connect-automation /app/main.py --upload-video
