name: PushAction
on:
  push:
    branches: [ master ]
    paths-ignore:
      - .github/workflows/daily_tasks.yml
      - .github/workflows/lambda.yml
      - .github/workflows/sched.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Cancel previous runs
        uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch git repository
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Build container image
        run: |
          cd $GITHUB_WORKSPACE/repo
          docker build --no-cache --force-rm -t "linaroits/connect-automation" .
  